import { execSync, spawnSync } from 'node:child_process';

import type { FindingsReport } from './findings.js';

export interface PRResult {
  url: string | null;
  branch: string;
  body: string;
}

function run(cmd: string, cwd: string): string {
  return execSync(cmd, { cwd, encoding: 'utf8' }).trim();
}

export function applyAutoFixable(_cwd: string, _report: FindingsReport): { count: number; descriptions: string[] } {
  // Reserved for future auto-fix logic. For now we only open a discovery PR
  // pointing at the findings file. Automated rewrites of source require a
  // separate trusted scope and Claude review.
  return { count: 0, descriptions: [] };
}

export function openFindingsPR(cwd: string, report: FindingsReport, taskId: string): PRResult {
  const branch = `nyx/analysis-${taskId.toLowerCase()}`;
  try { run(`git checkout -b ${branch}`, cwd); } catch { run(`git checkout ${branch}`, cwd); }

  const findingsFile = 'NYX_FINDINGS.md';
  spawnSync('git', ['add', findingsFile], { cwd });

  const status = run('git status --porcelain', cwd);
  if (!status) return { url: null, branch, body: 'no changes to commit' };

  // Git author kept in sync with dispatcher/src/config.ts gitAuthorName/Email.
  // Set GIT_AUTHOR_NAME/EMAIL in .env to your real GitHub-linked identity so
  // Vercel commit-author SSO accepts the commit and GitHub Actions fires on
  // PR branch pushes.
  const authorName = (process.env.GIT_AUTHOR_NAME ?? 'Nyx Agent').replace(/"/g, '\\"');
  const authorEmail = (process.env.GIT_AUTHOR_EMAIL ?? 'nyx@localhost').replace(/"/g, '\\"');
  run(`git -c user.name="${authorName}" -c user.email="${authorEmail}" commit -m "nyx(${taskId}): findings report"`, cwd);

  try { run(`git push -u origin ${branch}`, cwd); } catch (err) {
    return { url: null, branch, body: `push failed: ${(err as Error).message}` };
  }

  const summary = Object.entries(report.summary)
    .filter(([, n]) => n > 0)
    .map(([sev, n]) => `${n} ${sev}`).join(', ');
  const title = `nyx(${taskId}): ${report.scanType} findings`;
  const body = `Generated by Nyx ${report.scanType}.\n\nSummary: ${summary || 'no findings'}\n\nSee ${findingsFile} on this branch.`;

  const res = spawnSync('gh', ['pr', 'create', '--title', title, '--body', body, '--head', branch], {
    cwd, encoding: 'utf8',
  });
  const out = `${res.stdout ?? ''}\n${res.stderr ?? ''}`;
  const urlMatch = out.match(/https?:\/\/\S+/);
  return { url: urlMatch?.[0] ?? null, branch, body };
}
