/**
 * Pipeline delivery stage (⑨) — terminal A: PR-ready + gate-green.
 *
 * v1 stops at PR-ready (moc-nyx-pipeline (Arachne)): push the
 * reconciled integration branch, open a PR (NO auto-merge — the operator
 * reviews + merges; "deploy is your manual step"), fire the existing
 * `task.production.deploy_required` detection, emit a delivery brief, and clean
 * up the base clone. Autonomous deploy + CI-wait + auto-migrate are v2.
 *
 * Testability: `buildDeliveryBrief` is pure; `detectPipelineDeploy` is thin git;
 * the PR push (`openDeliveryPR`) is real git+gh and is dependency-injected so
 * `runDelivery` is testable with a canned push result.
 */

import { execSync } from 'node:child_process';
import { existsSync, readdirSync, rmSync } from 'node:fs';
import { cleanupRunSecrets } from './run-secrets.js';
import { dirname, basename } from 'node:path';

import { audit } from '../audit.js';
import { config } from '../config.js';
import { changedFiles, detectDeployRequired } from '../deploy-detector.js';
import { isGreenfield, targetMode } from './target.js';
import type { PipelineRun } from './types.js';

export interface DeliveryResult {
  pr_url: string | null;
  pushed: boolean;
  deploy_targets: string[];
  matched_files: string[];
  brief: string;
}

export interface DeliveryDeps {
  /** Push the integration branch + open a PR; returns the PR URL (or null). */
  push?: (run: PipelineRun, baseBranch: string) => string | null;
  /** Skip the base-clone teardown (tests). */
  skipCleanup?: boolean;
}

function gitTry(cmd: string, cwd: string): string | null {
  try {
    return execSync(cmd, { cwd, stdio: ['ignore', 'pipe', 'pipe'], encoding: 'utf8' }).trim();
  } catch {
    return null;
  }
}

function baseBranchFor(run: PipelineRun): string {
  if (run.repo && config.gitTargets[run.repo]?.baseBranch) return config.gitTargets[run.repo]!.baseBranch;
  return 'main';
}

/**
 * Real PR push: rebase the integration branch onto the repo's base, force-with-
 * lease push it, open a PR. Deliberately NO auto-merge — terminal A is
 * PR-ready; the operator reviews + merges. Returns the PR URL or null.
 */
function openDeliveryPR(run: PipelineRun, baseBranch: string): string | null {
  const base = run.worktree_base;
  const branch = run.integration_branch;
  if (!base || !branch || !run.repo) return null;
  if (gitTry('git fetch origin', base) === null) return null;
  gitTry(`git checkout -q "${branch}"`, base);
  if (gitTry(`git rebase origin/${baseBranch}`, base) === null) {
    gitTry('git rebase --abort', base);
    return null;
  }
  if (gitTry(`git push --force-with-lease -u origin "${branch}"`, base) === null) return null;
  // Idempotency: a prior attempt may have already opened the PR before throwing.
  // `gh pr create` rejects a second PR for the same head, and gitTry would
  // collapse that into null, dropping the valid existing PR URL. Reuse it.
  const existing = gitTry(`gh pr view "${branch}" --json url,state --jq "select(.state==\\"OPEN\\") | .url"`, base);
  if (existing) {
    const existingUrl = existing.match(/https?:\/\/\S+/)?.[0] ?? null;
    if (existingUrl) {
      if (config.settings.pipeline.autoMerge) {
        gitTry(`gh pr merge --auto --squash "${branch}"`, base);
      }
      return existingUrl;
    }
  }
  const title = `${run.task_id}: ${run.prompt}`.slice(0, 200);
  const body = `Generated by the Nyx pipeline (run ${run.id}).\n\n${run.prompt}\n\nReview + merge when ready — deploy is a manual step.`;
  const out = gitTry(
    `gh pr create --base ${baseBranch} --title ${JSON.stringify(title)} --body ${JSON.stringify(body)} --head ${branch}`,
    base,
  );
  if (!out) return null;
  const prUrl = out.match(/https?:\/\/\S+/)?.[0] ?? out.trim();
  // Opt-in auto-merge (Settings -> pipeline.autoMerge). Best-effort: needs
  // auto-merge enabled on the repo; gitTry swallows failure. GitHub still waits
  // for required checks/approvals before merging.
  if (config.settings.pipeline.autoMerge) {
    gitTry(`gh pr merge --auto --squash "${branch}"`, base);
  }
  return prUrl;
}

/** deploy_required detection: integration diff vs base × repo deployPatterns. */
export function detectPipelineDeploy(run: PipelineRun, baseBranch: string): { matched: string[]; targets: string[] } {
  if (!run.repo || !run.worktree_base) return { matched: [], targets: [] };
  const target = config.gitTargets[run.repo];
  const patterns = target?.deployPatterns ?? [];
  if (patterns.length === 0) return { matched: [], targets: [] };
  const files = changedFiles(run.worktree_base, `origin/${baseBranch}`);
  const { matchedFiles } = detectDeployRequired(files, patterns);
  return { matched: matchedFiles, targets: matchedFiles.length ? target?.deployTargets ?? [] : [] };
}

export function buildDeliveryBrief(run: PipelineRun, result: { pr_url: string | null; deploy_targets: string[] }): string {
  const merged = (() => {
    try {
      const f = run.redux_findings ? (JSON.parse(run.redux_findings) as { merged?: string[]; held?: string[] }) : {};
      return { merged: f.merged ?? [], held: f.held ?? [] };
    } catch {
      return { merged: [], held: [] };
    }
  })();
  const greenfield = isGreenfield(run.repo);
  const L: string[] = [];
  L.push(`# Delivered — ${run.id}`);
  L.push('');
  L.push(`**Prompt:** ${run.prompt}`);
  L.push('');
  if (greenfield) {
    L.push(`**New local project:** \`${run.worktree_base}\` (branch \`${run.integration_branch}\`)`);
  } else {
    L.push(result.pr_url ? `**PR (review + merge):** ${result.pr_url}` : `**Integration branch:** ${run.integration_branch} (in ${run.worktree_base})`);
  }
  L.push(`**Gate:** green · **Integrated:** ${merged.merged.length} task(s)${merged.held.length ? ` · **left out:** ${merged.held.join(', ')}` : ''}`);
  L.push('');
  if (result.deploy_targets.length) {
    L.push('## ⚠️ Manual deploy required');
    for (const t of result.deploy_targets) L.push(`- ${t}`);
    L.push('');
  }
  if (greenfield) {
    L.push(`Green. **Your new project lives at \`${run.worktree_base}\`** — it's a standalone git repo (no remote). Open it, run it, and push it wherever you like when ready.`);
  } else {
    L.push('Green + PR-ready. **Deploy is your manual step** (autonomous deploy is v2).');
  }
  return L.join('\n');
}

/**
 * Remove the run's base clone + all its coder/diagnostic worktrees from disk.
 * Called on a delivered `done` (work is on origin) or an abort. Best-effort.
 */
export function cleanupRunArtifacts(run: PipelineRun): void {
  const base = run.worktree_base;
  // Greenfield's base IS the deliverable (Data/projects/<task>) — detach its
  // coder worktrees but NEVER delete the project itself.
  const keepBase = isGreenfield(run.repo);
  if (base && existsSync(base)) {
    // Detach worktrees first so git doesn't complain, then remove the base.
    const wts = gitTry('git worktree list --porcelain', base);
    if (wts) {
      for (const line of wts.split('\n')) {
        if (line.startsWith('worktree ')) {
          const p = line.slice('worktree '.length).trim();
          if (p && p !== base) gitTry(`git worktree remove --force "${p}"`, base);
        }
      }
    }
    if (!keepBase) {
      try {
        rmSync(base, { recursive: true, force: true });
      } catch {
        /* swallow */
      }
    }
  }
  // Sweep any stray /tmp/nyx-clone-<runid>* dirs (coder/diag worktrees).
  const prefixDir = dirname(config.cloneRootPrefix);
  const prefixName = basename(config.cloneRootPrefix);
  try {
    for (const entry of readdirSync(prefixDir)) {
      if (entry.startsWith(`${prefixName}${run.id}`)) {
        try {
          rmSync(`${prefixDir}/${entry}`, { recursive: true, force: true });
        } catch {
          /* swallow */
        }
      }
    }
  } catch {
    /* swallow */
  }
  cleanupRunSecrets(run.id);
}

export async function runDelivery(run: PipelineRun, deps: DeliveryDeps = {}): Promise<DeliveryResult> {
  const baseBranch = baseBranchFor(run);
  const pushFn = deps.push ?? openDeliveryPR;

  let prUrl: string | null = null;
  if (targetMode(run.repo) === 'external') {
    prUrl = pushFn(run, baseBranch);
  }
  const { matched, targets } = detectPipelineDeploy(run, baseBranch);
  if (matched.length > 0) {
    // Reuse the established deploy-required event so the portal surfaces it.
    audit('task.production.deploy_required', 'pipeline.delivery', {
      taskId: run.task_id,
      repo: run.repo,
      matchedFiles: matched,
      deployTargets: targets,
    });
  }
  const brief = buildDeliveryBrief(run, { pr_url: prUrl, deploy_targets: targets });
  const result: DeliveryResult = { pr_url: prUrl, pushed: prUrl !== null, deploy_targets: targets, matched_files: matched, brief };

  // The orchestrator emits `pipeline.delivered` (the terminal marker) with this
  // result; runDelivery only owns the deploy_required event + cleanup.
  if (!deps.skipCleanup) cleanupRunArtifacts(run);
  return result;
}
